#' netVisual_STcellchat
#'
#' netVisual_STcellchat draws the circos plot for cellular communication with spatial informatioin taken into account
#'
#' @param cellchat a CellChat object generated by the STIE::get_STcellchat() function
#' @param cell_dist a matrix representing the distance between cell pairs
#' @param cell_types a vector of character values representing the cell type, with the name being the cell_id
#' @param color_use a vector of character values representing the colors of cell types. The cell types are ranked based on the alphabetical order
#'
#' 
#' @author Shijia Zhu, \email{shijia.zhu@@utsouthwestern.edu}
#' @export
#'
#' @references
#'
#' @seealso \code{\link{get_STcellchat}}; \code{\link{plot_STcellchat}}; 
#' 
#' 
netVisual_STcellchat = function(cellchat, cell_dist, cell_types, color_use=NULL)
{
    
    weight = cellchat@net$weight
    
    cell_pair = weight*0
    
    for(k in 1:nrow(cell_dist))
    {
        #cat(k,"\n")
        i = cell_dist$i[k]
        j = cell_dist$j[k]
        ci = cell_types[i]
        cj = cell_types[j]
        cell_pair[ci, cj] = cell_pair[cj, ci] = cell_pair[ci, cj] + 1
        #cell_pair[cj, ci] = cell_pair[cj, ci] + 1
    }
    
    groupSize <- as.numeric(table(cellchat@idents))
    cell_pair2 = cell_pair
    diag(cell_pair2) = 0
    
    mfrow = par()$mfrow
    mar = par()$mar
    
    par(mfrow=c(3,2))
    par(mar=c(2,2,2,2))
    netVisual_circle(weight, color.use=color_use, vertex.weight = groupSize, weight.scale = T, label.edge= F, title.name = "Interaction weights/strength")
    netVisual_circle(weight*cell_pair, color.use=color_use, vertex.weight = groupSize, weight.scale = T, label.edge= F, title.name = "Weighted number of interactions")
    
    netVisual_circle( weight*(cell_pair-cell_pair2), color.use=color_use, vertex.weight = groupSize, weight.scale = T, label.edge= F, title.name = "Weighted number of interactions (Within)")
    netVisual_circle( weight*cell_pair2, color.use=color_use, vertex.weight = groupSize, weight.scale = T, label.edge= F, title.name = "Weighted number of interactions (Between)")
    
    netVisual_circle(cell_pair, color.use=color_use, vertex.weight = groupSize, weight.scale = T, label.edge= F, title.name = "Cell pairs")
    
    par( mfrow=mfrow )
    par( mar=mar)
    
}



