#' rescue_missing_cells identify cell types for the missing cells falling in gap area between spots based on the learned STIE model
#'
#' @param STIE_result a STIE object generated by the STIE() function
#' @param cells_on_spot_new a data frame by the get_cells_on_spot() function representing missing cells that are not in STIE_result
#' @param merge_STIE_result a boolean value indicating whether to merge the result of missing cells with STIE_result
#'
#' @return A list containing the follow components:
#' \itemize{
#'  \item {lambda} a numeric value representing the shrinkage penalty of nuclear morphology, which is the same data frame cells_on_spot with the input
#'  \item {mu} a vector of numeric values representing the means of morphological features
#'  \item {sigma} a vector of numeric values representing the standard deviations of morphological features
#'  \item {PE_on_spot} a matrix of cell type probabilities for each spot estimated from the spot gene expression, where the row is the spot and column is the cell type
#'  \item {PM_on_cell} a matrix of cell type probabilities for each cell estimated from the cellular morphological features, where the row is the cell and column is the cell type
#'  \item {PME_uni_cell} a matrix of cell type probabilities for each cell estimated from both spot gene expression and cellular morphological features, where the row is the cell and column is the cell type
#'  \item {cell_types} a vector of character values representing the cell type for each cell, where the names(cell_types) are the unique cell ids
#'  \item {uni_cell_types} a vector of character values representing the cell type of unqiue cells with redundant cells eliminated 
#'  \item {Signature} a matrix of gene expression in gene X cell type. During deconvolution, it is the same with the input. During clustering, it is the re-estimated signature from the ST data. 
#'  \item {cells_on_spot} a data frame representing the cells on spots along with the cellular morphological features, which is the same data frame cells_on_spot with the input
#' }
#' 
#' @author Shijia Zhu, \email{shijia.zhu@@utsouthwestern.edu}
#' @export
#'
#' @references
#'
#' @seealso \code{\link{get_cells_on_spot}}; \code{\link{STIE}};
#' 
rescue_missing_cells <- function(STIE_result, cells_on_spot_new, merge_STIE_result=TRUE)
{
  
    lambda <- STIE_result$lambda
    mu <- STIE_result$mu
    sigma <- STIE_result$sigma
    PE_on_spot <- STIE_result$PE_on_spot
    PM_on_cell <- STIE_result$PM_on_cell
    PME_uni_cell <- STIE_result$PME_uni_cell
    cell_types <- STIE_result$cell_types
    uni_cell_types <- STIE_result$uni_cell_types
    Signature <- STIE_result$Signature
    cells_on_spot <- STIE_result$cells_on_spot
    
    missing_cells_on_spot = subset(cells_on_spot_new, 
                                   ! cells_on_spot_new$cell_id %in% cells_on_spot$cell_id &
                                   cells_on_spot_new$spot %in% cells_on_spot$spot)
    
    features = colnames(mu)
    spot_id = as.character(missing_cells_on_spot$spot)
    cell_id = as.character(missing_cells_on_spot$cell_id)
    
    if(length(cell_id)==0) {
        
        cat( "no missing cells \n" )
        if(merge_STIE_result) {
            result = STIE_result
        } else {
            result = NULL
        }
        
    } else {
        
        cat( "rescuing ", length(unique(cell_id)), "missing cells\n" )
        
        PM_on_cell = calculate_morphology_probability(missing_cells_on_spot, features, mu, sigma )
        PE_on_cell = PE_on_spot[ match(spot_id,rownames(PE_on_spot)) ,  ]
        
        PME_on_cell = t( apply(PM_on_cell*PE_on_cell,1,function(x)x/sum(x)) )
        PME_uni_cell = apply(PME_on_cell, 2, function(x) tapply(x, cell_id, max) )
        PME_uni_cell = PME_uni_cell[ match( cell_id, rownames(PME_uni_cell) ) , ]
        cell_types = colnames(PME_uni_cell)[apply(PME_uni_cell, 1, which.max)]
        names(cell_types) = rownames(PME_uni_cell)
        
        uni_cell_types = tapply( cell_types, names(cell_types), function(x) x[1] )
        
        if(merge_STIE_result) {
            
            lambda <- STIE_result$lambda
            mu <- STIE_result$mu
            sigma <- STIE_result$sigma
            PE_on_spot <- STIE_result$PE_on_spot
            PM_on_cell <- rbind(STIE_result$PM_on_cell, PM_on_cell) 
            PME_uni_cell <- rbind(STIE_result$PME_uni_cell, PME_uni_cell) 
            cell_types <- c(STIE_result$cell_types, cell_types)
            uni_cell_types <- c(STIE_result$uni_cell_types, uni_cell_types)
            Signature <- STIE_result$Signature
            cells_on_spot <- rbind(STIE_result$cells_on_spot, missing_cells_on_spot)
        }
        
        result <- list(lambda=lambda,
                       mu=mu, 
                       sigma=sigma, 
                       PE_on_spot = PE_on_spot,
                       PM_on_cell = PM_on_cell,
                       PME_uni_cell = PME_uni_cell, 
                       cell_types=cell_types,
                       uni_cell_types=uni_cell_types,
                       Signature=Signature,
                       cells_on_spot=cells_on_spot)
    } 
    
    result
    
}

